name: date_bin
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/DanMossa/date_bin

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0