name: date_bin
description: A Dart library that provides a dateBin function for binning timestamps into a specified interval 
  aligned with a specified origin, similar to the date_bin function in Postgres.
version: 1.0.0
repository: https://github.com/DanMossa/date_bin

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0